sub:
 - https://bitbucket.org/huwo1/proxy_nodes/raw/b90856fe7cb9c666223f3ad41c87d0e60c711590/proxy.md
 - https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub
 - https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity
 - https://raw.githubusercontent.com/wrfree/free/main/v2
 - https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
 - https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
 - https://raw.githubusercontent.com/adiwzx/freenode/main/adispeed.txt
 - https://raw.githubusercontent.com/freefq/free/master/v2
 - https://raw.githubusercontent.com/xiyaowong/freeFQ/main/v2ray
 - http://94.23.116.185:7794/clash/proxies
 - http://101.132.255.205:1234/clash/proxies
 - https://pc.adlionvm.tk/clash/proxies
 - https://sspool.herokuapp.com/clash/proxies
 - https://proxypool.laowang.me/clash/proxies
 - https://free886.herokuapp.com/clash/proxies
 - https://us-proxypool.herokuapp.com/clash/proxies
 - https://eu-proxypool.herokuapp.com/clash/proxies
 - https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
 - https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
 - https://raw.githubusercontent.com/Rokate/Proxy-Sub/main/clash/clash_v2ray.yml
 - https://raw.githubusercontent.com/Rokate/Proxy-Sub/main/clash/clash_trojan.yml
 - https://clash.221207.xyz/pubclashyaml
 - https://raw.githubusercontent.com/mahdibland/get_v2/main/pub/combine.yaml
 - https://raw.githubusercontent.com/mahdibland/get_v2/main/pub/jiang.yaml
local: ["into.yaml","../../Clash.yaml"]
